namespace TransactionReport
{
    public class Regions
    {
        public int[] HongKong
        {
            get
            {
                return new int[]
                {
                    (int)Countries.Hong_Kong,
                    (int)Countries.China,
                    (int)Countries.Spain,
                    (int)Countries.Austria,
                    (int)Countries.Afghanistan
                };
            }
        }

        public int[] Japan
        {
            get
            {
                return new int[] 
                { 
                    (int)Countries.Japan
                };
            }
        }

    }
    public enum Countries
    {
        Afghanistan = 1,
        Aland_Islands = 2,
        United_States = 3,
        Albania = 4,
        Algeria = 5,
        United_Kingdom = 6,
        Brazil = 7,
        Portugal = 8,
        France = 9,
        Germany = 10,
        Netherlands = 11,
        Spain = 12,
        Poland = 13,
        American_Samoa = 14,
        Andorra = 15,
        Angola = 16,
        Anguilla = 17,
        Antarctica = 18,
        Antigua_and_Barbuda = 19,
        Argentina = 20,
        Armenia = 21,
        Austria = 22,
        Switzerland = 23,
        Australia = 24,
        Sweden = 25,
        Denmark = 26,
        Finland = 27,
        Norway = 28,
        Iceland = 29,
        Italy = 30,
        Ireland = 31,
        China = 32,
        Russia = 33,
        Japan = 34,
        Aruba = 35,
        Azerbaijan = 36,
        Bahamas = 37,
        Bahrain = 38,
        Bangladesh = 39,
        Barbados = 40,
        Belarus = 41,
        Belgium = 42,
        Belize = 43,
        Benin = 44,
        Bermuda = 45,
        Bhutan = 46,
        Bolivia = 47,
        Bonaire, _Saint_Eustatius_and_ = 48,
        Bosnia_and_Herzegovina = 49,
        Botswana = 50,
        Bouvet_Island = 51,
        British_Indian_Ocean_Territor = 52,
        British_Virgin_Islands = 53,
        Brunei = 54,
        Bulgaria = 55,
        Burkina_Faso = 56,
        Burundi = 57,
        Cambodia = 58,
        Cameroon = 59,
        Canada = 60,
        Cape_Verde = 61,
        Cayman_Islands = 62,
        Central_African_Republic = 63,
        Chad = 64,
        Chile = 65,
        Christmas_Island = 66,
        Cocos_Islands = 67,
        Colombia = 68,
        Comoros = 69,
        Cook_Islands = 70,
        Costa_Rica = 71,
        Croatia = 72,
        Cuba = 73,
        Curacao = 74,
        Cyprus = 75,
        Czech_Republic = 76,
        Democratic_Republic_of_the_Co = 77,
        Djibouti = 78,
        Dominica = 79,
        Dominican_Republic = 80,
        East_Timor = 81,
        Ecuador = 82,
        Egypt = 83,
        El_Salvador = 84,
        Equatorial_Guinea = 85,
        Eritrea = 86,
        Estonia = 87,
        Ethiopia = 88,
        Falkland_Islands = 89,
        Faroe_Islands = 90,
        Fiji = 91,
        French_Guiana = 92,
        French_Polynesia = 93,
        French_Southern_Territories = 94,
        Gabon = 95,
        Gambia = 96,
        Georgia = 97,
        Ghana = 99,
        Gibraltar = 100,
        Greece = 101,
        Greenland = 102,
        Grenada = 103,
        Guadeloupe = 104,
        Guam = 105,
        Guatemala = 106,
        Guernsey = 107,
        Guinea = 108,
        Guinea_Bissau = 109,
        Guyana = 110,
        Haiti = 111,
        Heard_Island_and_McDonald_Isl = 112,
        Honduras = 113,
        Hong_Kong = 114,
        Hungary = 115,
        India = 116,
        Indonesia = 117,
        Iran = 118,
        Iraq = 119,
        Isle_of_Man = 120,
        Israel = 121,
        Ivory_Coast = 122,
        Jamaica = 123,
        Jersey = 124,
        Jordan = 125,
        Kazakhstan = 126,
        Kenya = 127,
        Kiribati = 128,
        Kosovo = 129,
        Kuwait = 130,
        Kyrgyzstan = 131,
        Laos = 132,
        Latvia = 133,
        Lebanon = 134,
        Lesotho = 135,
        Liberia = 136,
        Libya = 137,
        Liechtenstein = 138,
        Lithuania = 139,
        Luxembourg = 140,
        Macao = 141,
        Macedonia = 142,
        Madagascar = 143,
        Malawi = 144,
        Malaysia = 145,
        Maldives = 146,
        Mali = 147,
        Malta = 148,
        Marshall_Islands = 149,
        Martinique = 150,
        Mauritania = 151,
        Mauritius = 152,
        Mayotte = 153,
        Mexico = 154,
        Micronesia = 155,
        Moldova = 156,
        Monaco = 157,
        Mongolia = 158,
        Montenegro = 159,
        Montserrat = 160,
        Morocco = 161,
        Mozambique = 162,
        Myanmar = 163,
        Namibia = 164,
        Nauru = 165,
        Nepal = 166,
        Netherlands_Antilles = 167,
        New_Caledonia = 168,
        New_Zealand = 169,
        Nicaragua = 170,
        Niger = 171,
        Nigeria = 172,
        Niue = 173,
        Norfolk_Island = 174,
        North_Korea = 175,
        Northern_Mariana_Islands = 176,
        Oman = 177,
        Pakistan = 178,
        Palau = 179,
        Palestinian_Territory = 180,
        Panama = 181,
        Papua_New_Guinea = 182,
        Paraguay = 183,
        Peru = 184,
        Philippines = 185,
        Pitcairn = 186,
        Puerto_Rico = 187,
        Qatar = 188,
        Republic_of_the_Congo = 189,
        Reunion = 190,
        Romania = 191,
        Rwanda = 192,
        Saint_Barthelemy = 193,
        Saint_Helena = 194,
        Saint_Kitts_and_Nevis = 195,
        Saint_Lucia = 196,
        Saint_Martin = 197,
        Saint_Pierre_and_Miquelon = 198,
        Saint_Vincent_and_the_Grenadi = 199,
        Samoa = 200,
        San_Marino = 201,
        Sao_Tome_and_Principe = 202,
        Saudi_Arabia = 203,
        Senegal = 204,
        Serbia = 205,
        Serbia_and_Montenegro = 206,
        Seychelles = 207,
        Sierra_Leone = 208,
        Singapore = 209,
        Sint_Maarten = 210,
        Slovakia = 211,
        Slovenia = 212,
        Solomon_Islands = 213,
        Somalia = 214,
        South_Africa = 215,
        South_Georgia_and_the_South_S = 216,
        South_Korea = 217,
        South_Sudan = 218,
        Sri_Lanka = 219,
        Sudan = 220,
        Suriname = 221,
        Svalbard_and_Jan_Mayen = 222,
        Swaziland = 223,
        Syria = 224,
        Taiwan = 225,
        Tajikistan = 226,
        Tanzania = 227,
        Thailand = 228,
        Togo = 229,
        Tokelau = 230,
        Tonga = 231,
        Trinidad_and_Tobago = 232,
        Tunisia = 233,
        Turkey = 234,
        Turkmenistan = 235,
        Turks_and_Caicos_Islands = 236,
        Tuvalu = 237,
        US_Virgin_Islands = 238,
        Uganda = 239,
        Ukraine = 240,
        United_Arab_Emirates = 241,
        United_States_Minor_Outlying_ = 242,
        Uruguay = 243,
        Uzbekistan = 244,
        Vanuatu = 245,
        Vatican = 246,
        Venezuela = 247,
        Vietnam = 248,
        Wallis_and_Futuna = 249,
        Western_Sahara = 250,
        Yemen = 251,
        Zambia = 252,
        Zimbabwe = 253
    }
}
